### PR TITLE
doc - historical & PDF version tab in navbar

### PR DESCRIPTION
**Pull request by Shekharrajak**
#### Deployed URL

https://pr-29-scipy-sphinx-theme-v2.surge.sh

### CODE REVIEW

**Comment by rgommers** [comment]
So this is the _"Historical & PDF version"_ link in the right top corner:

image

The principle of linking to that page is right. I'm not sure that pdf is worth mentioning there. Perhaps _"Other doc versions"_?

What would also be nice is to have a small banner that's red and warns the user if they're not looking at the latest version. Because that's often an issue, and this top corner link doesn't make it clear that that's the case.

**Comment by mattip** [comment]
I thought the idea was to have a javascript-based version pull-down like at the top of the [python documentation page](https://docs.python.org/3/library/functions.html), and changing the pulldown will redirect to that version of the documentation. Notification that this is not the devdoc version would also be good

**Comment by Shekharrajak** [comment]
> The principle of linking to that page is right. I'm not sure that pdf is worth mentioning there. Perhaps "Other doc versions"?

Thanks for review. I will do this change.

> What would also be nice is to have a small banner that's red and warns the user if they're not looking at the latest version. Because that's often an issue, and this top corner link doesn't make it clear that that's the case.

I was looking for that solution but didn't get any proper solution for it in sphinx. It looks like we need to add that 'old version' warning banner manually(may be during make command) when we create build and store it in numpy/doc repository.

>I thought the idea was to have a javascript-based version pull-down like at the top of the python documentation page, and changing the pulldown will redirect to that version of the documentation. Notification that this is not the devdoc version would also be good

Yeah I thought about it but numpy.org/doc will serve the same purpose. May be we can add it as well and after clicking on specific version it will redirect to the same page with that selected version. 

I will search for similar technique in sphinx.

**Comment by mattip** [comment]
I don't think sphinx does this. The [scikit-image site](https://scikit-image.org/docs/dev/user_guide/transforming_image_data.html#color-manipulation) doc site does something like what you started. @tylerjereddy started to [work on this] in numpy/numpy#12097 for numpy but got stuck on the template formatting.

**Comment by Shekharrajak** [comment]
Thanks @mattip for sharing the PR link. I will do research on it how can we do it in sphinx or using any sphinx module.

**Comment by mattip** [comment]
Bokeh has this https://docs.bokeh.org/en/dev/ via [javascript](https://github.com/bokeh/bokeh/blob/f96e18f22eb2afc70b45371e93e38f155d05ecfd/sphinx/source/bokeh/scripts.html) and a json file

**Pull request merged**
